### ISSUE TITLE
ZIP decoding with multiple files

### ISSUE THREAD

**Issue by ddpwnage** [USArmyResearchLab/Dshell#10]
In the file `Dshell/decode.py` , you have a function `expandCompressedFile` with the parameters `fname` (file name), `verbose` (a seemingly boolean value indicating verbose output), and `tmpdir` (a temporary directory the files output to). However, there's a comment at the beginning of the function saying `Expand a file compressed with gzip, bzip2, or zip. Only handles zip files with one file. Need to add handling for zip files containing multiple files.`

I haven't learned Python or what it can do, but it looks like, in this statement:
`elif ext == '.zip':
            print "Enter password for .zip file [default:none]:",
            pswd=raw_input()
            z = zipfile.ZipFile(fname)
            f = z.open(z.namelist()[0],'r',pswd)`

Where `f` is the first file of `fname` (meaning `z` is the actual ZIP archive), a coder would need to implement some sort of `for` loop that adds values for `f` that is equal to the file index `0` of `z` (the first file in) to the file index (and it may be coded something like this, again, I don't know Python well enough to say so, but I do know VB, and I'm using the equivalent of that) `z.Items - 1` (the last file).

The function itself would have to be converted to use and output `string arrays` rather than a simple `string`. I don't know how to code it, but someone else might.

**Comment by wglodek** [comment]
Yes, this is still a TODO item.  We will implement support for multiple files in an archive (gzip, zip, bzip2).   Thank you for pointing it out.

**Comment by MasonGallo** [comment]
@ddpwnage thanks for pointing this out.

@wglodek  I have done this a few times recently, so I should be able to get something today/tomorrow if you're not doing yourself sooner - I'll make a pull request.

**Comment by dek443** [comment]
The Python 2 version of Dshell is now deprecated and frozen as Release v2.4.10. We are closing all Pull Requests and 	Issues associated with that version, as Dshell development has shifted to the current version for Python 3. Thank you for your support.
