### ISSUE TITLE
Add test suite

### ISSUE THREAD

**Issue by pstch** [USArmyResearchLab/Dshell#12]
This project is really nice, and seems like a really powerful development base for network forensics.

Since it was uploaded to GitHub, it has gathered quite a lot of attention, and I think that many people would be eager to contribute. Because of this, I think that a proper test suite would be really helpful for Dshell.

I am willing to do this myself, and I'm adding this ticket to know if anyone else has started to do some work on this matter.

Does anyone have initial ideas on how to properly add a test suite to Dshell ?

**Comment by ralfra** [comment]
Interesting idea. Try to create something and I will support while learning...

**Comment by dek443** [comment]
The Python 2 version of Dshell is now deprecated and frozen as Release v2.4.10. We are closing all Pull Requests and 	Issues associated with that version, as Dshell development has shifted to the current version for Python 3. Thank you for your support.
