### ISSUE TITLE
Deprecation warning running decode

### ISSUE THREAD

**Issue by JeffSoh** [USArmyResearchLab/Dshell#121]
Hello, I'm getting the following warning running decode -p dns...

/usr/local/lib/python3.8/site-packages/dshell/decode.py:490: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats
  header, packet = capture.next()

Running Python 3.8.5 and just pulled down the latest release of Dshell today. From Goggling, it looks like the issue is with PyArg_Parse? Thanks.

**Comment by dev195** [comment]
Unfortunately, it looks like this is an issue with the third-party pcapy library we use for reading pcap files. I see they have a [pull request](https://github.com/helpsystems/pcapy/pull/68) to fix that warning, but it might be worth creating an issue with their repository. 

If you see the warning show up anywhere else, please let us know, but we will close this specific issue.
