### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by zinking** [USArmyResearchLab/Dshell#16]
can not download these from mac 
would you mind adding support for mac

BTW, this looks brilliant.

**Comment by ninuxsoft** [comment]
Python isn't aleady installed in mac ? 
 Christian BaconAnalyste-Intégrateur de systèmes / IT Systems EngineerInformaticien / Computer Scientist
NINUXSOFT
Consultant en intégration de systèmes - Unix, F5, Embarqués.
Courriel : ninuxsoft@yahoo.ca
Cellulaire : (418) 576-0664 

     On Tuesday, February 3, 2015 11:56 AM, heubergen <notifications@github.com> wrote:
   

 Have you already tried to install python for mac? You will need it.Basically every linux program should work on mac...—

**Comment by heubergen** [comment]
Maybe not the right version, @zinking should say us what exactly not work.
Maybe theres only a missing Prerequisites

**Comment by sweetmandm** [comment]
@zinking It seems to work fine for me on OSX -- if you can provide more info about which part broke for you and what the error messages were, it would probably help diagnose your issue.

**Comment by ThomasWunderlich** [comment]
Mac OSX comes with Python. Check what version by running python --version and making sure that it's python 2.7.*
@heubergen  Mac is built on bsd, not linux so there are some differences and many programs can act unexpectedly

**Comment by zinking** [comment]
sudo apt-get install python-crypto python-dpkt python-ipy python-pypcap
sudo: apt-get: command not found

I use home-brew to install the dependencies. @ThomasWunderlich  can you let me know your steps?
probably worth adding them to the README.

**Comment by sweetmandm** [comment]
good point -- homebrew might not have what you need, I used [pip](https://pypi.python.org/pypi/pip/) which is a package manager for python dependencies.

You can check if you already have pip installed with:

    which pip

If it doesn't print a path, you need to install it. `easy_install` should come with python, so this should work:

    sudo easy_install pip

Then you can install the deps:

    pip install crypto
    pip install dpkt
    pip install pycap
    pip install ipy

And finally you should now be able to

   make

**Comment by RyPeck** [comment]
Should the install process be moved to use the `pip -r` functionality instead of apt-get? Not sure what OS's you want to support.

https://pip.pypa.io/en/latest/user_guide.html#requirements-files

**Comment by zinking** [comment]
@sweetmandm thanks, it works perfectly now.

**Comment by ThomasWunderlich** [comment]
It probably makes sense to switch to using pip, which is portable across a number of linux/bsd distros. Probably worth updating the README and install script

**Comment by virtadpt** [comment]
Have you considered setting up a virtualenv sandbox (https://virtualenv.pypa.io/en/latest/), activating it, and then running pip in there to keep everything neat and clean?  It makes things significantly easier (plus keeps different versions of the same module required by different apps from overlapping).

**Comment by rmac75** [comment]
If ok with the devs, I will make a docker.io image on docker hub with the
latest. We can link to it via github, and issue solved. Will advise when it
is up. BTW, you all rock, fired up to see dshell on github.

-r


On Wed, Feb 4, 2015 at 5:38 PM, The Doctor <notifications@github.com> wrote:

> Have you considered setting up a virtualenv sandbox (
> https://virtualenv.pypa.io/en/latest/), activating it, and then running
> pip in there to keep everything neat and clean? It makes things
> significantly easier (plus keeps different versions of the same module
> required by different apps from overlapping).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USArmyResearchLab/Dshell/issues/16#issuecomment-72955457>
> .
>



-- 
Seek elegance.
