### ISSUE TITLE
is it possible to include the sample pcap in the project?

### ISSUE THREAD

**Issue by zinking** [USArmyResearchLab/Dshell#25]
I haven't do the network data capture and analysis for quite a while. mainly because being lazy.
is it possible to include those pcap files mentioned in the README file ?

**Comment by mboman** [comment]
Wouldn't it be better if a download script was created instead? Putting a lot of unnecessary binary blobs in the repository isn't cool.

**Comment by RyPeck** [comment]
If it is small enough it isn't too much trouble. But there are more than a few websites hosting PCAP could download samples from.

http://www.netresec.com/?page=PcapFiles
http://www.malware-traffic-analysis.net/ (MALWARE Samples)
https://code.google.com/p/security-onion/wiki/Pcaps (list of samples @Security-Onion has included)

**Comment by rmac75** [comment]
We can link to the honeynet projects pcap such as
http://www.honeynet.org/files/attack-trace.pcap_.gz if that is helpful.

On Thu, Feb 5, 2015 at 4:15 AM, Michael Boman <notifications@github.com>
wrote:

> Wouldn't it be better if a download script was created instead? Putting a
> lot of unnecessary binary blobs in the repository isn't cool.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USArmyResearchLab/Dshell/issues/25#issuecomment-73015772>
> .
>



-- 
Seek elegance.

**Comment by wglodek** [comment]
@RyPeck @rmac75 These are great resources for pcap.  At this time there is no plan to include pcap in the repo.

**Comment by RyPeck** [comment]
@wglodek A good in between would be to provide a link to a sample that exercises some of the capabilities of Dshell! Maybe you could find one from some of the sources @rmac75 and I pointed out.
