### ISSUE TITLE
Recommended install location?

### ISSUE THREAD

**Issue by ThomasWunderlich** [USArmyResearchLab/Dshell#29]
Is there a recommended install location? It looks like we're supposed to install under your user's home directory.

**Comment by necrose99** [comment]
https://github.com/necrose99/Dshell/blob/master/setup.cfg
https://github.com/necrose99/Dshell/blob/master/setup.py 
been tinkering with a Genric UNIX install for setup/distutils 

feal free to fork them -- as a good SYSTEM level installer  my pyskills are not all top flight by any-means. 

(and or pyfreeeze for windows etc) 
Setup tools can drop out an rpm 
as well , DPKG if used.can drop out debian packages if set up.  

hears my personal targets 
[emake] (https://devmanual.gentoo.org/eclass-reference/eutils.eclass/)..... or [python-distutils-single-r1] (https://devmanual.gentoo.org/eclass-reference/python-single-r1.eclass/index.html)
would be a plus to far easier to deploy , with ebuilds 
however the pwd option can't be overridden 
ie buildroot and install root cant be passed. into current make, 
2to-3 would let run under python 3 perhaps stable'ly etc. 
.dshellrc stores path of gentoo /var/tmp/{$pv}/workdir/{$pv}  Dshell-9999  
(version 9999 is for live un-versioned) 
i'm not all that good with SED to fix the intended target root. ie dshellrc file paths. 

/opt/Dshell
SYM   /opt/Dshell/doc  to  /usr/share/doc/Dshell most proper distro installers install docks to /user/share/doc/{$PV} 
SYM   /opt/Dshell/share     /usr/share/GeoIP     (geo ip installs tables hear on Gentoo based systems I would surmise similar for debian redhar etc) so linking to Dshell root as share works . as geoip updates dshell can use them. 

SYMLINK /opt/Dshell/dshell*   /usr/bin  ( deshell && deshell-decode. )

https://packages.debian.org/search?keywords=geoip
https://packages.gentoo.org/packages/dev-libs/geoip


however subsequent packaging can rebuild Dshell ie 
Dshell-addons  or others that would add on 3rd party plugins or add-on modules not direclty contributed. 
, git pull copy to /decoders run generate-dshellrc.py or some triv mini fork generate-dshellrc-addons.py & generate-dshellrc-missing-docs.py  to freshen docs & pyc of plugins would make life easy. 
 
**wish listed, **
Makefile. Here is an example at what the ‘dist:’ goal might look like:

distdir = $(PACKAGE)-$(VERSION)
dist: Makefile
	rm -fr $(distdir)
	mkdir $(distdir)
	chmod 777 $(distdir)
	for file in $(DISTFILES); do \
	  ln $$file $(distdir) 2>/dev/null || cp -p $$file $(distdir); \
	done
	for subdir in $(SUBDIRS); do \
	  mkdir $(distdir)/$$subdir || exit 1; \
	  chmod 777 $(distdir)/$$subdir; \
	  (cd $$subdir && $(MAKE) $@) || exit 1; \
	done
	tar chozf $(distdir).tar.gz $(distdir)
	rm -fr $(distdir)
Makefile. Here is an example at what the ‘dist:’ goal might look like:

distdir = $(PACKAGE)-$(VERSION)
dist: Makefile
	rm -fr $(distdir)
	mkdir $(distdir)
	chmod 777 $(distdir)
	for file in $(DISTFILES); do \
	  ln $$file $(distdir) 2>/dev/null || cp -p $$file $(distdir); \
	done
	for subdir in $(SUBDIRS); do \
	  mkdir $(distdir)/$$subdir || exit 1; \
	  chmod 777 $(distdir)/$$subdir; \
	  (cd $$subdir && $(MAKE) $@) || exit 1; \
	done
	tar chozf $(distdir).tar.gz $(distdir)
	rm -fr $(distdir)
Makefile. Here is an example at what the ‘dist:’ goal might look like:
 make install DESTDIR=/some/staging/directory PREFIX=/opt/local

**Comment by dek443** [comment]
The Python 2 version of Dshell is now deprecated and frozen as Release v2.4.10. We are closing all Pull Requests and 	Issues associated with that version, as Dshell development has shifted to the current version for Python 3. Thank you for your support.
