### ISSUE TITLE
Overview page for rip-http and other decoders

### ISSUE THREAD

**Issue by pexnet** [USArmyResearchLab/Dshell#30]
It would be nice to have a overview page for the rip-http decoder.  I'm thinking of a page much like the one for chaosreader  http://chaosreader.sourceforge.net/Chaos01/index.html  but with a more modern look with filtering and searching. I could be based on http://www.datatables.net/ for example. I'm unsure where in the architecture this would fit. Maybe it would be appropriate to create a post processing step that will kick in when all streams are processed.  I think an overview would be useful for other decoders as well.  One other way to solve this is that the decoder creates a file,  with a summary of all streams and associated files, that could be processed by a stand alone tool to create an overview.

**Comment by dek443** [comment]
The Python 2 version of Dshell is now deprecated and frozen as Release v2.4.10. We are closing all Pull Requests and 	Issues associated with that version, as Dshell development has shifted to the current version for Python 3. Thank you for your support.
