### ISSUE TITLE
Documentation  README.md unclear regarding /share/GeoIP/

### ISSUE THREAD

**Issue by gluesniffmonkey** [USArmyResearchLab/Dshell#4]
README.md states:
1. Configure pygeoip by moving the MaxMind data files (GeoIP.dat, GeoIPv6.dat, GeoIPASNum.dat, GeoIPASNumv6.dat) to /share/GeoIP/"

Should that be /home/[username]/share/GeoIP 

or 

sudo mkdir /usr/local/share/GeoIP/ ?

It is a bit unclear in README.md.

**Comment by RyPeck** [comment]
What's the installation method you guys are using for the MaxMind data?

**Comment by gluesniffmonkey** [comment]
In the end I found this. https://www.digitalocean.com/community/tutorials/an-introduction-to-analytics-and-content-testing-with-nginx

Using wget and gunzip.

**Comment by wglodek** [comment]
@gluesniffmonkey It does seem a bit unclear.  Would this change to the README.md clarify the install:

2. Configure pygeoip by moving the MaxMind data files (GeoIP.dat, GeoIPv6.dat, GeoIPASNum.dat, GeoIPASNumv6.dat) to &lt;install-location&gt;/share/GeoIP/

If this doesn't help, what would you suggest?

**Comment by EvansNyamandi24** [comment]
Do you need to install any kind of software to open these types of files?

**Comment by philoes** [comment]
The precision makes it clearer. 
My own issue with using geoip data from within Dshell on pure debian was, that pygeoip was setup initially with too strict permissions:

# ls -l /usr/local/lib/python2.7/dist-packages/pygeoip
insgesamt 144
-rw------- 1 root staff 17371 Feb  7 13:10 const.py
-rw------- 1 root staff 27502 Feb  7 13:10 const.pyc
-rw------- 1 root staff 21585 Feb  7 13:10 __init__.py
-rw------- 1 root staff 20390 Feb  7 13:10 __init__.pyc
-rw------- 1 root staff 23062 Feb  7 13:10 timezone.py
-rw------- 1 root staff 16914 Feb  7 13:10 timezone.pyc
-rw------- 1 root staff  1408 Feb  7 13:10 util.py
-rw------- 1 root staff  1908 Feb  7 13:10 util.pyc

So as regular user I wasn't able to import pygeoip... After having fixed that, Dshell> decode -d dns-cc etc. worked as a charm. Thank you very much for providing a very nice and capable tool!

**Comment by dek443** [comment]
The Python 2 version of Dshell is now deprecated and frozen as Release v2.4.10. We are closing all Pull Requests and 	Issues associated with that version, as Dshell development has shifted to the current version for Python 3. Thank you for your support.
