### ISSUE TITLE
When I run the capture in interface mode (i.e. -i) I dont get output untill i CTRL+C

### ISSUE THREAD

**Issue by ileathan** [USArmyResearchLab/Dshell#42]
I beleive the expected output should be a realtime view of the dns queries.

I tried `decode -i eth0 -d dns > log && tail -f log` but same problem.

**Comment by wglodek** [comment]
Thanks for bringing this to our attention.  Pull requests #43 and #44 should enable the real time view of DNS queries.  For viewing and saving real time DNS requests/queries, I would recommend using the following command: `decode -i eth0 -d dns --nobuf | tee log.txt`

**Comment by ileathan** [comment]
:+1: feels much better now!

I was wondering what the the steps are for not running as root? Either way thanks!

**Comment by jiamo** [comment]
How about -o pcap=test.pcap , there are some logic error in decoder.py to  assigne the var `out`
