### ISSUE TITLE
Bug in large-flows.py decoder

### ISSUE THREAD

**Issue by slinkard** [USArmyResearchLab/Dshell#51]
The large-flows.py decoder appears to have a bug in the code in line 24.  The decoder is designed for flows 1MB or larger.  This would 1048576 bytes.  Line 24 incorrectly omits the last digit:

self.min = 104857 \* self.size

should be

self.min = 1048576 \* self.size

**Comment by wglodek** [comment]
@slinkard Thanks!   Fixed in  80ad7a3df023c907a7407448ef60c02f375e426f. The developer responsible for this bug has been promoted to middle management and should no longer be a problem.

**Comment by FlorianHeigl** [comment]
@wglodek well congrats ;-)

**Comment by dek443** [comment]
The Python 2 version of Dshell is now deprecated and frozen as Release v2.4.10. We are closing all Pull Requests and 	Issues associated with that version, as Dshell development has shifted to the current version for Python 3. Thank you for your support.
