### ISSUE TITLE
How to compile and run on MAC OSX

### ISSUE THREAD

**Issue by haikieu** [USArmyResearchLab/Dshell#52]
Hello everyone,

I'm try to compile the source code in MAC OSX, 

Do you have any guide on this ?

**Comment by raul5660** [comment]
you should be able to run make

**Comment by stevenliuit** [comment]
mac os is open source it?

**Comment by jaredestroud** [comment]
If make fails for you, try this:
1) Manually install the dependencies
```
sudo pip install dpkt
sudo pip install crypto
sudo pip install pypcap
sudo pip install ipy
sudo pip install pygeoip
```
2) Run ```make```

3) ./dshell

**Comment by chr1sk0n** [comment]
@stevenliuit The guys from Apple are using open source tools, but OS X itself its not.

**Comment by dek443** [comment]
The Python 2 version of Dshell is now deprecated and frozen as Release v2.4.10. We are closing all Pull Requests and 	Issues associated with that version, as Dshell development has shifted to the current version for Python 3. Thank you for your support.
