### ISSUE TITLE
Fedora 21 runtime error

### ISSUE THREAD

**Issue by JeffSoh** [USArmyResearchLab/Dshell#53]
I'm getting this error running Dshell on a new install on Fedora 21, kernel 3.19.17-200:

Traceback (most recent call last):                                                                                                                                                            
  File "/root/Dshell/trunk/bin/decode", line 891, in main                                                                                                                                     
    decoder.capture = pcap.pcap(pcapfile)                                                                                                                                                     
AttributeError: 'module' object has no attribute 'pcap'

I have all the Fedora equivalents of the prereqs, as far as i know, and have this running on another Fedora 21 box without error. Anyone seen this? 

Code is:

try:
                    if not pcap:
                        raise NotImplementedError(
                            "pcap support not implemented")
                    decoder.capture = pcap.pcap(pcapfile)

Running Python 2.7.8, have libpcap, libpcap-devel and pylibpcap installed.

**Comment by dev195** [comment]
The problem might be pylibpcap. Dshell uses pypcap instead of pylibpcap, both of which are unhelpfully imported with "import pcap".
Try using [pypcap](https://pypi.python.org/pypi/pypcap/1.1.1) instead.

**Comment by JeffSoh** [comment]
Thank you, that fixed it.
